import { Orientation, Position } from '../../../primitives.js';
import GalaxySymbol, {
  instance as galaxyInstance,
} from '../../../symbols/galaxySymbol.js';
import LotusSymbol, {
  instance as lotusInstance,
} from '../../../symbols/lotusSymbol.js';
import Symbol from '../../../symbols/symbol.js';

/**
 * An isometry of the grid, written in doubled coordinates so that axes and centers landing on
 * cell corners are represented exactly:
 *
 * ```
 * X' = m00 * X + m01 * Y + t0
 * Y' = m10 * X + m11 * Y + t1
 * ```
 *
 * where `X = 2x` and `Y = 2y` for a cell at `(x, y)`. All fields are integers.
 */
export interface Symmetry {
  readonly m00: number;
  readonly m01: number;
  readonly m10: number;
  readonly m11: number;
  readonly t0: number;
  readonly t1: number;
}

export const IDENTITY: Symmetry = {
  m00: 1,
  m01: 0,
  m10: 0,
  m11: 1,
  t0: 0,
  t1: 0,
};

/** The transformation `a` applied after `b`. */
export function compose(a: Symmetry, b: Symmetry): Symmetry {
  return {
    m00: a.m00 * b.m00 + a.m01 * b.m10,
    m01: a.m00 * b.m01 + a.m01 * b.m11,
    m10: a.m10 * b.m00 + a.m11 * b.m10,
    m11: a.m10 * b.m01 + a.m11 * b.m11,
    t0: a.m00 * b.t0 + a.m01 * b.t1 + a.t0,
    t1: a.m10 * b.t0 + a.m11 * b.t1 + a.t1,
  };
}

export function symmetryKey(symmetry: Symmetry): string {
  return `${symmetry.m00},${symmetry.m01},${symmetry.m10},${symmetry.m11},${symmetry.t0},${symmetry.t1}`;
}

export function linearKey(symmetry: Symmetry): string {
  return `${symmetry.m00},${symmetry.m01},${symmetry.m10},${symmetry.m11}`;
}

/** The image of a cell under the symmetry. Only integral for cell-preserving symmetries. */
export function apply(symmetry: Symmetry, x: number, y: number): Position {
  return {
    x: (symmetry.m00 * 2 * x + symmetry.m01 * 2 * y + symmetry.t0) / 2,
    y: (symmetry.m10 * 2 * x + symmetry.m11 * 2 * y + symmetry.t1) / 2,
  };
}

/** True when the symmetry maps every cell center to a cell center. */
export function isCellPreserving(symmetry: Symmetry): boolean {
  const origin = apply(symmetry, 0, 0);
  return Number.isInteger(origin.x) && Number.isInteger(origin.y);
}

/** True when the symmetry is a non-zero translation, which no finite region can absorb. */
export function isTranslation(symmetry: Symmetry): boolean {
  return (
    symmetry.m00 === 1 &&
    symmetry.m01 === 0 &&
    symmetry.m10 === 0 &&
    symmetry.m11 === 1 &&
    (symmetry.t0 !== 0 || symmetry.t1 !== 0)
  );
}

function halfTurn(sx: number, sy: number): Symmetry {
  return { m00: -1, m01: 0, m10: 0, m11: -1, t0: 2 * sx, t1: 2 * sy };
}

function reflection(
  sx: number,
  sy: number,
  orientation: Orientation
): Symmetry {
  switch (orientation) {
    case Orientation.Up:
    case Orientation.Down:
      return { m00: -1, m01: 0, m10: 0, m11: 1, t0: 2 * sx, t1: 0 };
    case Orientation.Right:
    case Orientation.Left:
      return { m00: 1, m01: 0, m10: 0, m11: -1, t0: 0, t1: 2 * sy };
    case Orientation.UpRight:
    case Orientation.DownLeft:
      return { m00: 0, m01: -1, m10: -1, m11: 0, t0: sx + sy, t1: sx + sy };
    case Orientation.DownRight:
    case Orientation.UpLeft:
      return { m00: 0, m01: 1, m10: 1, m11: 0, t0: sx - sy, t1: sy - sx };
  }
}

/**
 * The symmetry that the given symbol imposes on its region, or an empty list if the symbol does
 * not impose one (either because it is not a symmetry symbol, or because it is placed so that its
 * axis or center does not map cell centers to cell centers).
 */
export function symmetriesOf(symbol: Symbol): Symmetry[] {
  let symmetry: Symmetry | null = null;
  if (symbol.id === galaxyInstance.id) {
    const galaxy = symbol as GalaxySymbol;
    symmetry = halfTurn(2 * galaxy.x, 2 * galaxy.y);
  } else if (symbol.id === lotusInstance.id) {
    const lotus = symbol as LotusSymbol;
    symmetry = reflection(2 * lotus.x, 2 * lotus.y, lotus.orientation);
  }
  if (!symmetry || !isCellPreserving(symmetry)) return [];
  return [symmetry];
}

export interface SymmetryGroup {
  /** Every element of the generated group, including the identity. */
  readonly elements: readonly Symmetry[];
  /** True when the group contains a non-zero translation, so it is infinite. */
  readonly infinite: boolean;
}

/**
 * Closes the given symmetries under composition.
 *
 * Every generator has a linear part in the symmetry group of the square, which has eight
 * elements, so a finite group generated by them has at most eight elements: anything larger must
 * contain a translation.
 */
export function generateGroup(
  generators: readonly Symmetry[],
  limit = 16
): SymmetryGroup {
  const elements = new Map<string, Symmetry>([
    [symmetryKey(IDENTITY), IDENTITY],
  ]);
  const queue = generators.slice();
  while (queue.length > 0) {
    const next = queue.pop()!;
    const key = symmetryKey(next);
    if (elements.has(key)) continue;
    if (isTranslation(next)) return { elements: [], infinite: true };
    if (elements.size >= limit) return { elements: [], infinite: true };
    elements.set(key, next);
    for (const existing of [...elements.values()]) {
      queue.push(compose(next, existing), compose(existing, next));
    }
  }
  return { elements: [...elements.values()], infinite: false };
}
