import GridData from '../../../grid.js';
import InsightContext from '../insightContext.js';
import InsightLemma from './insightLemma.js';
import { area, cell } from '../helper.js';
import { Color, Position } from '../../../primitives.js';
import Symbol from '../../../symbols/symbol.js';
import { Region } from '../stores/regionStore.js';
import {
  apply,
  generateGroup,
  symmetryKey,
  symmetriesOf,
  Symmetry,
} from '../types/symmetry.js';

interface Constraint {
  symbol: Symbol;
  symmetry: Symmetry;
}

/**
 * Disconnects regions that cannot be merged because their combined region could not satisfy every
 * symmetry symbol it would contain.
 *
 * A region holding a galaxy or a lotus must be invariant under the corresponding isometry, so a
 * merged region must be invariant under the whole group generated by the symmetries it contains.
 * Merging is impossible when either:
 *
 * 1. The generated group contains a translation, which happens as soon as two symbols demand
 *    distinct parallel axes, or two different centers. No finite region is invariant under it.
 * 2. A cell of the merged region has no room for its image, because the mirrored cell is off-grid,
 *    does not exist, or is known to belong to neither region.
 *
 * The second case covers regions that carry no symmetry symbol of their own as well: their cells
 * still have to be matched by the other region's symbols.
 */
export default class DisconnectIncompatibleSymmetries extends InsightLemma {
  public readonly id = 'disconnect-incompatible-symmetries';

  public isApplicable(grid: GridData): boolean {
    return !!grid.findSymbol(symbol => symmetriesOf(symbol).length > 0);
  }

  public apply(context: InsightContext): boolean {
    const regions = [...context.regions.regions.values()];
    const constraints = regions.map(region => this.constraintsOf(region));
    let progress = false;
    for (let i = 0; i < regions.length; i++) {
      for (let j = i + 1; j < regions.length; j++) {
        if (constraints[i].length === 0 && constraints[j].length === 0)
          continue;
        const regionA = regions[i];
        const regionB = regions[j];
        if (
          regionA.color !== Color.Gray &&
          regionB.color !== Color.Gray &&
          regionA.color !== regionB.color
        )
          continue;
        if (
          context.regions.isDisconnected(
            regionA.positions[0],
            regionB.positions[0]
          )
        )
          continue;
        const blocker = this.mergeBlocker(
          context,
          regionA,
          regionB,
          constraints[i],
          constraints[j]
        );
        if (!blocker) continue;
        const proof = this.proof().difficulty(2);
        const modified = context.regions.addDisconnected(
          regionA.positions[0],
          regionB.positions[0],
          proof.describe(blocker.description(regionA, regionB))
        );
        progress ||= modified;
      }
    }
    return progress;
  }

  /** The symmetry symbols of a region, each contributing one isometry. */
  private constraintsOf(region: Region): Constraint[] {
    const constraints: Constraint[] = [];
    const seen = new Set<Symbol>();
    for (const symbol of region.symbols) {
      if (seen.has(symbol)) continue;
      seen.add(symbol);
      for (const symmetry of symmetriesOf(symbol)) {
        constraints.push({ symbol, symmetry });
      }
    }
    return constraints;
  }

  private mergeBlocker(
    context: InsightContext,
    regionA: Region,
    regionB: Region,
    constraintsA: Constraint[],
    constraintsB: Constraint[]
  ): { description: (a: Region, b: Region) => string } | null {
    const grid = context.grid;
    const constraints = [...constraintsA, ...constraintsB];
    const group = generateGroup(constraints.map(c => c.symmetry));
    if (group.infinite)
      return {
        description: (a, b) =>
          `${area(a.positions[0])} and ${area(b.positions[0])} must be separate because the symmetry symbols at ${cell(constraints.map(c => c.symbol))} would force the combined region to be infinitely large`,
      };

    const mapA = regionA.getRegionMap();
    const mapB = regionB.getRegionMap();
    const exists = (x: number, y: number): boolean =>
      x >= 0 &&
      y >= 0 &&
      x < grid.width &&
      y < grid.height &&
      grid.getTile(x, y).exists;
    const member = (x: number, y: number): boolean =>
      exists(x, y) && (mapA[y][x] === true || mapB[y][x] === true);
    const outsider = (x: number, y: number): boolean =>
      !exists(x, y) || (mapA[y][x] === false && mapB[y][x] === false);

    const cells: Position[] = [];
    for (let y = 0; y < grid.height; y++) {
      for (let x = 0; x < grid.width; x++) {
        if (member(x, y)) cells.push({ x, y });
      }
    }

    for (const symmetry of group.elements) {
      for (const pos of cells) {
        const image = apply(symmetry, pos.x, pos.y);
        if (!outsider(image.x, image.y)) continue;
        const owner = constraints.find(
          c => symmetryKey(c.symmetry) === symmetryKey(symmetry)
        );
        return {
          description: (a, b) =>
            `${area(a.positions[0])} and ${area(b.positions[0])} must be separate because ${cell(pos)} would need a matching cell at ${cell(image)} ${
              owner
                ? `for the symmetry symbol at ${cell(owner.symbol)}`
                : `under the combined symmetries at ${cell(constraints.map(c => c.symbol))}`
            }, but that cell cannot belong to the combined region`,
        };
      }
    }
    return null;
  }
}
